# Generated by Django 4.2.14 on 2024-08-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_booking_email_remove_booking_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='email', max_length=254),
            preserve_default=False,
        ),
    ]
