# Generated by Django 4.2.14 on 2024-08-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
